export const enum ROLE {
	SUPERADMIN = 'SUPERADMIN',
	CLIENT = 'CLIENT',
	AGENT = 'AGENT',
	COSTUMER = 'COSTUMER',
}

export const enum STATUS {
	ACTIVE = 'ACTIVE',
	PENDING = 'PENDING',
	DELETED = 'DELETED',
	SUSPENDED = 'SUSPENDED',
}
